# Generated by Django 3.2.14 on 2022-07-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('date_of_booking', models.DateField()),
                ('booked_time', models.CharField(choices=[('1', '5pm to 7pm'), ('2', '7pm to 9pm'), ('3', '9pm to close')], default='5pm-7pm', max_length=4)),
                ('num_of_guests', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6)], default='1', max_length=7)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
    ]
