# Generated by Django 3.2.13 on 2022-07-01 16:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.UUIDField(default=uuid.UUID('06aa9a31-a517-420c-bc73-34ee7c8aa8f4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
