# Generated by Django 3.2.14 on 2022-07-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookit', '0002_auto_20220727_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='booked_time',
            field=models.CharField(choices=[('17-10', '5pm to 7pm'), ('19-21', '7pm to 9pm'), ('21-23', '9pm to close')], max_length=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='num_of_guests',
            field=models.CharField(choices=[('6', 6), ('4', 4), ('3', 3), ('1', 1), ('5', 5), ('2', 2)], max_length=7),
        ),
        migrations.AlterField(
            model_name='customer',
            name='table',
            field=models.CharField(choices=[(2, 'Table 3'), (10, 'Table 7'), (4, 'Table 1'), (2, 'Table 6'), (4, 'Table 5'), (4, 'Table 2'), (4, 'Table 4')], max_length=7),
        ),
    ]
