# Generated by Django 3.2.14 on 2022-07-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookit', '0002_customer_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='table',
            field=models.CharField(choices=[(4, 'Table 1'), (4, 'Table 2'), (2, 'Table 3'), (4, 'Table 4'), (4, 'Table 5'), (2, 'Table 6'), (10, 'Table 7')], max_length=7),
        ),
    ]
