# Generated by Django 3.2.14 on 2022-07-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookit', '0003_alter_customer_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='num_of_guests',
            field=models.CharField(choices=[('6', 6), ('5', 5), ('1', 1), ('3', 3), ('2', 2), ('4', 4)], default='1', max_length=7),
        ),
        migrations.AlterField(
            model_name='customer',
            name='table',
            field=models.CharField(choices=[(4, 'Table 1'), (4, 'Table 2'), (2, 'Table 3'), (10, 'Table 7'), (4, 'Table 5'), (2, 'Table 6'), (4, 'Table 4')], max_length=7),
        ),
    ]
