# Generated by Django 3.2.13 on 2022-07-03 18:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookit', '0003_alter_customer_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='available_tables',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='booking_duration',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='num_of_guests',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='status_of_booking',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.UUIDField(default=uuid.UUID('c017e2e2-1a20-4365-8994-4e7eb815db7e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_booking', models.TimeField()),
                ('booked_time', models.TimeField()),
                ('num_of_guests', models.IntegerField()),
                ('available_tables', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('status_of_booking', models.BooleanField(choices=[(True, 'Booked'), (False, 'Not Booked')], default=False)),
                ('which_tables', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookit.customer')),
            ],
            options={
                'ordering': ['booked_time'],
            },
        ),
    ]
