# Generated by Django 3.2.13 on 2022-07-03 18:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookit', '0004_auto_20220703_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ManyToManyField(to='bookit.Customer'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='which_tables',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.UUIDField(default=uuid.UUID('55665dd3-3717-4e16-9cc7-788eeb57ba3e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
