# Generated by Django 3.2.14 on 2022-07-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookit', '0005_auto_20220721_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='other_info',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='booked_time',
            field=models.CharField(choices=[('1', '5pm to 7pm'), ('2', '7pm to 9pm'), ('3', '9pm to close')], max_length=4),
        ),
        migrations.AlterField(
            model_name='customer',
            name='num_of_guests',
            field=models.CharField(choices=[('3', 3), ('6', 6), ('2', 2), ('4', 4), ('1', 1), ('5', 5)], max_length=7),
        ),
        migrations.AlterField(
            model_name='customer',
            name='table',
            field=models.CharField(choices=[(4, 'Table 2'), (2, 'Table 3'), (4, 'Table 5'), (10, 'Table 7'), (4, 'Table 1'), (2, 'Table 6'), (4, 'Table 4')], max_length=7),
        ),
    ]
