# Generated by Django 3.2.13 on 2022-07-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookit', '0006_alter_customer_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ManyToManyField(to='bookit.Customer', verbose_name='Customers'),
        ),
    ]
