# Generated by Django 3.2.13 on 2022-07-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookit', '0007_alter_booking_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_of_booking',
            field=models.DateField(),
        ),
    ]
