# Generated by Django 3.2.13 on 2022-07-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookit', '0008_alter_booking_date_of_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_time',
            field=models.CharField(max_length=15),
        ),
    ]
