# Generated by Django 3.2.13 on 2022-07-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookit', '0012_alter_booking_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ManyToManyField(to='bookit.Customer'),
        ),
    ]
