# Generated by Django 3.2.14 on 2022-07-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookit', '0014_remove_booking_available_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='num_of_guests',
            field=models.IntegerField(verbose_name=6),
        ),
    ]
