# Generated by Django 3.2.14 on 2022-07-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookit', '0015_alter_booking_num_of_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='num_of_guests',
            field=models.IntegerField(),
        ),
    ]
