# Generated by Django 3.2.14 on 2022-07-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookit', '0016_alter_booking_num_of_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_of_booking',
            field=models.DateTimeField(),
        ),
    ]
