# Generated by Django 3.2.14 on 2022-07-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookit', '0017_alter_booking_date_of_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='available_seats',
            field=models.CharField(choices=[('1', 4), ('2', 4), ('3', 2), ('4', 6), ('5', 4), ('6', 10)], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_time',
            field=models.CharField(choices=[('1', '5pm to 7pm'), ('2', '7pm to 9pm'), ('3', '9pm to close')], default='5pm-7pm', max_length=4),
        ),
        migrations.AlterField(
            model_name='booking',
            name='num_of_guests',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6)], default='1', max_length=7),
        ),
    ]
