# Generated by Django 3.2.14 on 2022-07-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookit', '0018_auto_20220719_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_of_booking',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
