# Generated by Django 3.2.14 on 2022-07-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookit', '0019_alter_booking_date_of_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='available_seats',
            field=models.CharField(choices=[('1', 4), ('2', 4), ('3', 2), ('4', 6), ('5', 4), ('6', 10)], default='Select', max_length=10),
        ),
    ]
