# Generated by Django 3.2.14 on 2022-07-19 13:46

import bookit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookit', '0021_alter_booking_available_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.CharField(default=None, max_length=10, verbose_name=bookit.models.Customer),
        ),
    ]
