# Generated by Django 3.2.14 on 2022-07-19 13:48

import bookit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookit', '0022_auto_20220719_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.CharField(default='Scott', max_length=10, verbose_name=bookit.models.Customer),
        ),
    ]
