# Generated by Django 3.2.14 on 2022-07-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookit', '0024_auto_20220719_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='booked_time',
            field=models.CharField(choices=[('1', '5pm to 7pm'), ('2', '7pm to 9pm'), ('3', '9pm to close')], default='5pm-7pm', max_length=4),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_of_booking',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='num_of_guests',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6)], default='1', max_length=7),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
