# Generated by Django 3.2.14 on 2022-07-19 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookit', '0025_auto_20220719_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_of_booking',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
